### ISSUE TITLE
Filepath as value of a property in windows platform

### ISSUE THREAD

**Issue by apoorvam** [dmotylev/goproperties#10]
Property which sets the value of a filepath in windows platform would be like :

`custom_path = C:\Users\abc`

But value of this property obtained using Load method would be like `C:Usersabc` as it escapes the slashes. 

Escaping slashes in the value of the property works. But this is not standard way of setting path in a properties file. (windows)

`custom_path = C:\\Users\\abc`

Is there a workaround for it? Any comments?

**Comment by dmotylev** [comment]
it is by design. use double backslash.
